#!/bin/sh
#
# ~/.sh.d/func
#
sprunge() {
  cat $1 | curl -F 'sprunge=<-' http://sprunge.us
}

extract() {
  if [ -f $1 ]; then
    case $1 in
      *.tar.bz2) tar xvjf $1 ;;
      *.tar.gz) tar xvzf $1 ;;
      *.tar.xz) tar xvf $1 ;;
      *.bz2) bunzip2 $1 ;;
      *.gz) gunzip $1 ;;
      *.tar) tar xvf $1 ;;
      *.tbz2) tar xvjf $1 ;;
      *.tgz) tar xvzf $1 ;;
      *.txz) tar xvf $1 ;;
      *.xz) unxz $1 ;;
      *.zip) unzip $1 ;;
      *.Z) uncompress $1 ;;
      *) echo 'cannot be extracted' ;;
    esac
  else
    echo 'not valid file'
  fi
}
